### ISSUE TITLE
Showing error after changing entry type name but not the handle

### ISSUE THREAD

**Issue by kevadamson** [confluxgroup/craft-level-entry-types#4]
So I've changed only the name but kept the handle the same yet it's showing the invalid parent errors on the entries listings page.

Latest version of plugin and version of Craft CMS.

**Comment by dreadfullyposh** [comment]
@kevadamson We'll try to replicate this.

**Comment by dreadfullyposh** [comment]
@kevadamson We tried this locally and weren't able to replicate this. A couple things:

1. Can you confirm, you tried changing the name of a section? Or were you changing an entry type name? (We tested both and didn't have an issue)

2. Can you let me know what the name was before and what you changed it to? And can you let me know what the handle is?

3. Can you check the browser console for any JavaScript errors related to the plugin and pass those alone if you find any?

Thanks,

Jeremy

**Comment by dreadfullyposh** [comment]
@kevadamson haven't heard back from you. Is this still an issue, or should I close this out?

**Comment by kevadamson** [comment]
Sorry yes, still getting the issue.

1. Entry type name.
2. From "- Level 1" to "- 1. Folder"; "- Level 2" to "- - 2. Overview" (the handles remain level1, level2 - which is what they are set to in the php file.
3. Nothing showing.

**Comment by dreadfullyposh** [comment]
Hm. I've copied and pasted your entry type names in exactly as you have them and there errors appear/disappear just fine depending on the levels defined in my config PHP file. 

Can you copy and paste your config file here as well as a screenshot of your Entries list?

**Comment by kevadamson** [comment]
Strangely it's now only top level folders showing the error:

![image](https://user-images.githubusercontent.com/1021744/102337696-b9318880-3f8a-11eb-9a61-f3785a5eac84.png)

```
<?php

return [
	'structures' => [
		'yourContent' => [
			1 => [
				'level1'
			],
			2 => [
				'level2'
			],
			3 => [
				'level3'
			],
			4 => [
				'level4'
			]
		],
		'packages' => [
			1 => [
				'level1'
			],
			2 => [
				'level2'
			],
			3 => [
				'level3'
			],
			4 => [
				'level4'
			]
		],
		'freeResources' => [
			1 => [
				'level1'
			],
			2 => [
				'level2'
			],
			3 => [
				'level3'
			],
			4 => [
				'level4'
			]
		]
	]
];
```

**Comment by dreadfullyposh** [comment]
I think we figured this out. Based on the config you provided, it looks like your entry type handles overlap between sections. I think this is causing confusion in our validation logic, which is causing errors to be shown even when the entries are in the correct hierarchy.

For a future version we can look into ways to isolate the entry type sets for each section, but I know that was a bit of a complicated ask when we were building the plugin out, due to the data the Craft provides in the DOM for the element list view.

Our solution for the moment would be to use unique entry type handles and see if that resolves the issue.

**Comment by kevadamson** [comment]
Oh OK. I'll try that and report back. Many thanks for being patient and taking the time to look in to this :)

**Comment by kevadamson** [comment]
Yeah that worked. Had to reconfigure my templates a little as I had templates shared between sections which pulled entries based on level and type name - now just pulling them based on level, as the type name is different.

**Comment by dreadfullyposh** [comment]
Awesome good to hear.
