### ISSUE TITLE
Multiple Issues: All Options Available, Not Working in Production

### ISSUE THREAD

**Issue by jacobgraf** [confluxgroup/craft-level-entry-types#5]
I just purchased this plugin and am seeing multiple issues.

In development, I can see/select any entry type. Like your screenshot, I would rather the unavailable entry types be grayed out and not selectable. If they try to save the entry with the wrong entry type, it allows the entry to save, but it also shows the error on top and in the entries list, but this is not ideal, I'd like to prevent them from selecting the wrong entry type from the beginning.

Also, the stuff above works in development, but in production, nothing is working. I have no idea why. I have verified the same config file exists in production and the plugin was successfully installed.

I'm stumped.

**Comment by jacobgraf** [comment]
**Development Versions:** https://cln.sh/ORPsHmBu80MOABnexRGu
**Production Versions:** https://cln.sh/5f1rz4ZeootScN5YJJon

**Comment by dreadfullyposh** [comment]
@jacobgraf can you add your Level Entry Types config file here? 

One thing that has caused issues in the past is duplicate entry types across multiple sections. That tends to confuse the validation logic.

**Comment by jacobgraf** [comment]
```
<?php

return [
	'structures' => [
		'shopify' => [
			1 => [
				'store'
            ],
            2 => [
				'product'
			],
            3 => [
				'variant'
			]
		]
	]
];
```

**Comment by jacobgraf** [comment]
I also just verified I am not using the same entry type for any sections. Also, this doesn't explain why it works in dev, but not in production when they are using the same everything (via project config)

**Comment by dreadfullyposh** [comment]
We'll do some testing. It's possible that a recent Craft update broke something.

As far as dev vs production, are you sure you did a composer install and the plugin is actually installed/enabled properly in production? We've never seen an issue with the plugin across environments.

**Comment by jacobgraf** [comment]
Yes, that was the first thing I verified. It's showing green and installed in plugins when I enable dev mode in production. I suppose I could try uninstall/reinstall in production, but it will bork my remote deploy. Let me try quick.

**Comment by dreadfullyposh** [comment]
Perhaps also check the permissions on the config file on prod? Maybe Craft isn't able to read it? May be worth checking the various log files too.

One other thing to look for is any errors in the browser console. That could clue us in.

**Comment by jacobgraf** [comment]
No dice on the complete uninstall/reinstall in production. Checking the other things.

**Comment by jacobgraf** [comment]
Permissions look fine. Nothing stands out in the logs. No console messages. I'm guessing it has something to do with one of the version mismatches from dev to prod. In dev I'm using php 7.3 and in prod 8. Also, in dev I'm using MySQL 5.7 and in prod 8.

**Comment by dreadfullyposh** [comment]
Ok thanks. We'll test locally with Craft 3.7 to see what's going on. Did you look for console errors on dev too? 

I'm at a bit of a loss on the production vs dev issue. The plugin itself doesn't touch the database at all, so the MySQL version wouldn't impact it. It's definitely possible the PHP version is an issue, but we can test that as well.

Will get back later today or tomorrow after we do some testing.

**Comment by jacobgraf** [comment]
Yes, I did. No console errors in dev either. Thanks!

**Comment by dreadfullyposh** [comment]
I just tested on Craft 3.7.14 with PHP 7.3 and it definitely disables the entry types in the dropdowns correctly.

Can you tell us what other plugins you have installed? Maybe something is conflicting with it. This plugin is almost entirely frontend related, so other plugins that modify the control panel interface with JS definitely have a chance of interfering.

**Comment by jacobgraf** [comment]
Did you try it with Craft 3.7 and PHP 8?

**Comment by jacobgraf** [comment]
![CleanShot 2021-09-30 at 10 20 04@2x](https://user-images.githubusercontent.com/146333/135483883-4e5e407d-5b9a-45ea-af96-881ceb4af2bc.jpg)

**Comment by dreadfullyposh** [comment]
Still checking PHP 8. 

The plugin list doesn't look too bad to me. It may be worth trying to disable them temporarily one at a time on dev to see if any of them has an impact on the functionality of Level Entry Types.

**Comment by jacobgraf** [comment]
I did that. No dice. Disabled them all.

**Comment by dreadfullyposh** [comment]
One last thought. What browser are you using? Can you try another one?

**Comment by jacobgraf** [comment]
I am using Brave. I'm on a Mac (Monterey Public Beta). Just tried Firefox and Safari. Same issues exist on both. Hmm.

**Comment by dreadfullyposh** [comment]
Ok. Can I see a screenshot of your entry types screen for the section in question and also a screenshot of your sections screen?

**Comment by jacobgraf** [comment]
![CleanShot 2021-09-30 at 11 20 43@2x](https://user-images.githubusercontent.com/146333/135493481-6244b63d-e23c-4d39-92a2-e902c941f098.jpg)

![CleanShot 2021-09-30 at 11 21 25@2x](https://user-images.githubusercontent.com/146333/135493541-159bdb42-b391-4dbf-ae13-5ce912b0b35f.jpg)

**Comment by kylecotter** [comment]
Hey @jacobgraf,

We’ve done some more testing on our end. 

Using Craft 3.7.12 as our base and installing the plugins in your screenshots, we setup envs running:
- PHP 7.3 with MySQL 5.7
- PHP 7.3 with MySQL 8
- PHP 8 with MySQL 5.7
- PHP 8 with MySQL 8

and cannot successfully reproduce your issue.

One last thing to try, can you clear all the Craft CMS caches on both dev and prod, as well as your browser, and see if that affects anything.

If not, can you please send a database backup, plus your composer.json and composer.lock files over to kyle@cotterinteractive.com and jeremy@confluxgroup.com so we can look into it on your install?
 
 Thanks!

**Comment by kylecotter** [comment]
Hi, @jacobgraf, any update here? Thanks!

**Comment by jacobgraf** [comment]
Sorry, yeah, I did try all of that. Same issue. I'll shoot the DB and other files over via email now!

**Comment by kylecotter** [comment]
@jacobgraf thanks for sending that over! Got it setup locally using PHP 7.3 and MySQL 5.7 and everything seemed to be working as expected on our setup when creating entries and modifying existing entries in a standard workflow of clicking entry links/new entry button, navigating to the edit entry screen, making adjustments, and clicking save.

<img width="1004" alt="Screen Shot 2021-10-04 at 10 48 21 PM" src="https://user-images.githubusercontent.com/505894/135952363-6b568fa4-ab03-43c9-947b-632904affadb.png">

We did however find that if you use Craft 3.7’s new infinitely nestable related element slide over panel the entry type selector in this view is indeed not performing any validation on your select options.

<img width="862" alt="Screen Shot 2021-10-04 at 10 50 00 PM" src="https://user-images.githubusercontent.com/505894/135952462-d3ba767f-3949-43dd-bb3c-8d37a6d592e0.png">

Can you confirm if your issue was in regards to adding and editing entries in the traditional workflow of click entry link -> edit entry page loads -> save, and not when working inside a Craft 3.7 nested relationship panel?

Thanks!

**Comment by jacobgraf** [comment]
I am so stumped. lol Yeah, I was using the normal edit process, not the nested stuff. This is what I see on my dev server.

![CleanShot 2021-10-06 at 08 51 16@2x](https://user-images.githubusercontent.com/146333/136216080-c0db38a0-fb37-4667-a31f-9d253ff618ec.jpg)

**Comment by dreadfullyposh** [comment]
At this point we're stumped as well since we were able to pull in your database and your Level Entry Types config and have the plugin work with a variety of PHP versions. It definitely seems like there may be some aggressive caching in place on your setups that is preventing the Level Entry Types JS from loading on your setups. You may want to look through your .htaccess files and comment out anything extra that's not in the base Craft one. Otherwise I'm not really sure where to go from here.

**Comment by eirabben** [comment]
Hi

I just opened PR #7 that should fix this issue.

**Comment by dreadfullyposh** [comment]
@jacobgraf We just released a new version with the fix @eirabben submitted. This should hopefully fix your issue.

**Comment by jacobgraf** [comment]
It's working great now! Thanks everybody!
