### ISSUE TITLE
The plugin could not be found in any version

### ISSUE THREAD

**Issue by helleholmsen** [confluxgroup/craft-level-entry-types#6]
Trying to install it with _composer require confluxgroup/level-entry-types_ does not work. Do I need php v8 or something? I'm using php v 7.4 in my project. This is the error message I get:

_Root composer.json requires confluxgroup/level-entry-types, it could not be found in any version, there may be a typo in the package name._

**Comment by helleholmsen** [comment]
I also tried adding it to composer.json directly like this:

`"confluxgroup/level-entry-types": "1.0.3"` or like this
`"confluxgroup/level-entry-types": "v1.0.3"`

and running` composer update` but I get the same error

**Comment by dreadfullyposh** [comment]
The package name is confluxgroup/craft-level-entry-types not confluxgroup/level-entry-types

**Comment by helleholmsen** [comment]
Ok, thanks:) Maybe update the documentation to that? Right now it says: `composer require confluxgroup/level-entry-types`

**Comment by kylecotter** [comment]
@helleholmsen definitely a typo on our side. We updated the README. Thanks for flagging!
